version: "3"

services:
  web:
    build: ./src/
    command: sh -c "python3 /app/main.py"
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy


  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - backend
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

  redis:
    image: redis:latest
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 50

networks:
  backend:
